language: dart
dart:
  - dev
install: true
script:
  - pub get
  - pub upgrade
  - dart bin/main.dart
  - pub run test/dart_console_app_example_test.dart
  - dart test/dart_console_app_example_test.dart
  - dartanalyzer --fatal-warnings bin/main.dart test/dart_console_app_example_test.dart
  - dartanalyzer --fatal-warnings lib/dart_console_app_example.dart test/dart_console_app_example_test.dart
  - dart2aot bin/main.dart bin/main.dart.aot
  - dartaotruntime bin/main.dart.aot
