name: dart_console_app_example
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/daggerok/dart-console-app-example/
author: Maksim Kostromin <daggerok@gmail.com>

environment:
  sdk: '>=3.6.0'

#dependencies:
#  path: 1.6.2

dev_dependencies:
  test:
dependencies:
  ffi: ^2.1.3
